# Generated by Django 4.2.6 on 2023-10-25 07:29

import ckeditor.fields
import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_user', models.BooleanField(default=False)),
                ('is_agent', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('is_builder', models.BooleanField(default=False)),
                ('is_flatmate', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CommentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('Mobile_number', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(default='', max_length=40)),
                ('message', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=100)),
                ('Mobile_number', models.CharField(blank=True, max_length=13)),
                ('email', models.EmailField(default='', max_length=40)),
                ('map', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DeveloperDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_type', models.CharField(choices=[('Buy', 'Buy'), ('Plots', 'Plots')], default='Buy', max_length=20)),
                ('image', models.ImageField(upload_to='Developer_images')),
                ('developer_name', models.CharField(max_length=100)),
                ('established_year', models.CharField(max_length=20)),
                ('total_projects', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DownloadForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('Mobile_number', models.CharField(blank=True, max_length=12)),
                ('email', models.EmailField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(default='', max_length=40)),
                ('message', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Featuredcollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('Commercial', 'Commercial'), ('Buy', 'Buy'), ('Plots', 'Plots'), ('Rent', 'Rent')], default='Buy', max_length=20)),
                ('image', models.ImageField(upload_to='Developer_images')),
                ('name', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='HousingExperts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_type', models.CharField(choices=[('Commercial', 'Commercial'), ('Buy', 'Buy'), ('Plots', 'Plots'), ('Rent', 'Rent')], default='Buy', max_length=20)),
                ('image', models.ImageField(upload_to='Developer_images')),
                ('developer_name', models.CharField(max_length=30)),
                ('established_year', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('total_projects', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=40)),
                ('area', models.CharField(max_length=30)),
                ('Agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Logo_images')),
            ],
        ),
        migrations.CreateModel(
            name='NewsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_type', models.CharField(choices=[('Commercial', 'Commercial'), ('Buy', 'Buy'), ('Plots', 'Plots'), ('Rent', 'Rent')], default='Buy', max_length=20)),
                ('main_title', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='News_images')),
                ('name', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=20)),
                ('article_by', models.CharField(max_length=40)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_Type', models.CharField(default='Residential', max_length=20)),
                ('Looking_for', models.CharField(choices=[('Apartment', 'Apartment'), ('Independent Floor', 'Independent Floor'), ('Independent House', 'Independent House'), ('Villa', 'Villa')], default='Apartment', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='residential_images')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='residential_images')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('developer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('Configuration', models.CharField(blank=True, max_length=100, null=True)),
                ('Avg_price', models.CharField(blank=True, max_length=100, null=True)),
                ('property_name', models.CharField(blank=True, max_length=100, null=True)),
                ('amenities_name', models.CharField(blank=True, max_length=100, null=True)),
                ('video_image', models.ImageField(blank=True, null=True, upload_to='video_images')),
                ('video', models.TextField(default='https://www.youtube.com/embed/tgbNymZ7vqY')),
                ('map_location', models.CharField(blank=True, max_length=100, null=True)),
                ('lc_map', models.TextField(default='https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3806.012976551304!2d78.429541!3d17.459093!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xd4a220dc7610156d!2sBrigade%20Citadel!5e0!3m2!1sen!2sin!4v1632476420684!5m2!1sen!2sin&rel=0')),
                ('brouchure_image1', models.ImageField(blank=True, null=True, upload_to='brouchure_images')),
                ('brouchure_image2', models.ImageField(blank=True, null=True, upload_to='brouchure_images')),
                ('brouchure_image3', models.ImageField(blank=True, null=True, upload_to='brouchure_images')),
                ('brouchure_image4', models.ImageField(blank=True, null=True, upload_to='brouchure_images')),
                ('brouchure_image5', models.ImageField(blank=True, null=True, upload_to='brouchure_images')),
                ('File_upload', models.FileField(upload_to='Files')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active?')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured?')),
                ('is_sale', models.BooleanField(default=False, verbose_name='Is Sale?')),
                ('Agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Experts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.housingexperts')),
                ('Features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.featuredcollections')),
                ('developers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developerdetails', to='housingapp.developerdetails')),
            ],
            options={
                'permissions': (('can_publish_projectdetail', 'Can publish project detail'),),
            },
        ),
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_Type', models.CharField(default='Residential', max_length=20)),
                ('Looking_for', models.CharField(choices=[('Apartment', 'Apartment'), ('Independent Floor', 'Independent Floor'), ('Independent House', 'Independent House'), ('Villa', 'Villa')], default='Apartment', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rent_images')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='rent_images')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True)),
                ('developer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('configuration', models.CharField(blank=True, max_length=100, null=True)),
                ('amenities_name', models.CharField(blank=True, max_length=100, null=True)),
                ('map_location', models.CharField(blank=True, max_length=100, null=True)),
                ('lc_map', models.TextField(default='https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3806.012976551304!2d78.429541!3d17.459093!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xd4a220dc7610156d!2sBrigade%20Citadel!5e0!3m2!1sen!2sin!4v1632476420684!5m2!1sen!2sin&rel=0')),
                ('Agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Experts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.housingexperts')),
                ('Features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.featuredcollections')),
            ],
            options={
                'permissions': (('can_publish_projectdetail', 'Can publish project detail'),),
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Reviews_images')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='Reviews_images')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.projectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='RentReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Reviews_images')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='Reviews_images')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rent_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.rentprojectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='RentLikedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.rentprojectdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery_images')),
                ('rent_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.rentprojectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='RentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rent_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.rentprojectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='RentAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Amenities_images')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('rent_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.rentprojectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAdvantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content1', models.CharField(blank=True, max_length=100, null=True)),
                ('content2', models.CharField(blank=True, max_length=100, null=True)),
                ('content3', models.CharField(blank=True, max_length=100, null=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.projectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='PlotsProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_Type', models.CharField(choices=[('Plots', 'Plots'), ('Agricultural Lands', 'Agricultural Lands')], default='Office', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plot_images')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='plot_images')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('project_by', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('configuration', models.CharField(blank=True, max_length=100, null=True)),
                ('Avg_price', models.CharField(blank=True, max_length=100, null=True)),
                ('property_name', models.CharField(blank=True, max_length=100, null=True)),
                ('amenities_name', models.CharField(blank=True, max_length=100, null=True)),
                ('video_image', models.ImageField(blank=True, null=True, upload_to='video_images')),
                ('video', models.TextField(default='https://www.youtube.com/embed/tgbNymZ7vqY')),
                ('map_location', models.CharField(blank=True, max_length=100, null=True)),
                ('lc_map', models.TextField(default='https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3806.012976551304!2d78.429541!3d17.459093!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xd4a220dc7610156d!2sBrigade%20Citadel!5e0!3m2!1sen!2sin!4v1632476420684!5m2!1sen!2sin&rel=0')),
                ('brouchure_image1', models.ImageField(blank=True, null=True, upload_to='brouchure_images')),
                ('brouchure_image2', models.ImageField(blank=True, null=True, upload_to='brouchure_images')),
                ('brouchure_image3', models.ImageField(blank=True, null=True, upload_to='brouchure_images')),
                ('brouchure_image4', models.ImageField(blank=True, null=True, upload_to='brouchure_images')),
                ('brouchure_image5', models.ImageField(blank=True, null=True, upload_to='brouchure_images')),
                ('File_upload', models.FileField(upload_to='Files')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active?')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured?')),
                ('is_sale', models.BooleanField(default=False, verbose_name='Is Sale?')),
                ('Agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Experts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.housingexperts')),
                ('Features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.featuredcollections')),
                ('developers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.developerdetails')),
            ],
            options={
                'permissions': (('can_publish_projectdetail', 'Can publish project detail'),),
            },
        ),
        migrations.CreateModel(
            name='PlotReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Reviews_images')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='Reviews_images')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('plot_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.plotsprojectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='PlotLikedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.plotsprojectdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlotGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery_images')),
                ('plot_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.plotsprojectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='PlotFloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='floorplan_images')),
                ('plot_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.plotsprojectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='PlotDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('plot_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.plotsprojectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='PlotAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Amenities_images')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('plot_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.plotsprojectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='PlotAdvantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content1', models.CharField(blank=True, max_length=100, null=True)),
                ('content2', models.CharField(blank=True, max_length=100, null=True)),
                ('content3', models.CharField(blank=True, max_length=100, null=True)),
                ('plot_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.plotsprojectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='News_images')),
                ('title', ckeditor.fields.RichTextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('article_by', models.CharField(max_length=40)),
                ('date', models.CharField(max_length=20)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.newsdetails')),
            ],
        ),
        migrations.CreateModel(
            name='LikedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.projectdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery_images')),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.projectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='floorplan_images')),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.projectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.projectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_Type', models.CharField(default='Commercial', max_length=20)),
                ('Looking_for', models.CharField(choices=[('Office', 'Office'), ('Retail Shop', 'Retail Shop'), ('Ware House', 'Ware House'), ('Showroom ', 'Showroom')], default='Office', max_length=20)),
                ('commercial_type', models.CharField(choices=[('Recently Added properties for Rent', 'Recently Added properties for Rent'), ('Recently Added properties for sale', 'Recently Added properties for sale')], default='Recently Added properties for sale', max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Commercial_images')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='Commercial_images')),
                ('main_title', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('project_by', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('Configuration', models.CharField(blank=True, max_length=100, null=True)),
                ('Avg_price', models.CharField(blank=True, max_length=100, null=True)),
                ('Agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Experts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.housingexperts')),
                ('Features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.featuredcollections')),
            ],
            options={
                'permissions': (('can_publish_projectdetail', 'Can publish project detail'),),
            },
        ),
        migrations.CreateModel(
            name='CommercialLikedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.commercialprojectdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommercialGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery_images')),
                ('commercial_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.commercialprojectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('commercial_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.commercialprojectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Amenities_images')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('commercial_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.commercialprojectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='News_images')),
                ('name', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=20)),
                ('description', ckeditor.fields.RichTextField()),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.newsdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Amenities_images')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.projectdetail')),
            ],
        ),
    ]
