# Generated by Django 4.1 on 2023-10-27 10:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatmateChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flatmate_choices', models.CharField(choices=[('Food Available', 'Food Available'), ('Boys', 'Boys'), ('Private Room', 'Private Room'), ('Girls', 'Girls')], default='Boys', max_length=20)),
                ('image', models.ImageField(upload_to='Flat_images')),
            ],
        ),
        migrations.AlterModelOptions(
            name='commercialprojectdetail',
            options={'permissions': (('can_publish_commercialprojectdetail', 'Can publish commercial project detail'),)},
        ),
        migrations.AlterModelOptions(
            name='plotsprojectdetail',
            options={'permissions': (('can_publish_plotsprojectdetail', 'Can publish plots project detail'),)},
        ),
        migrations.AlterModelOptions(
            name='rentprojectdetail',
            options={'permissions': (('can_publish_rentprojectdetail', 'Can publish rent project detail'),)},
        ),
        migrations.AlterField(
            model_name='commercialprojectdetail',
            name='commercial_type',
            field=models.CharField(choices=[('Recently Added properties for sale', 'Recently Added properties for sale'), ('Recently Added properties for Rent', 'Recently Added properties for Rent')], default='Recently Added properties for sale', max_length=40),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Buy', 'Buy'), ('Rent', 'Rent'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Buy', 'Buy'), ('Rent', 'Rent'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsdetails',
            name='news_type',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Buy', 'Buy'), ('Rent', 'Rent'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='Features',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_details', to='housingapp.featuredcollections'),
        ),
        migrations.CreateModel(
            name='FlatmateProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='plot_images')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='plot_images')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('project_by', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('sharing', models.CharField(blank=True, max_length=100, null=True)),
                ('lc_map', models.TextField(default='https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3806.012976551304!2d78.429541!3d17.459093!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xd4a220dc7610156d!2sBrigade%20Citadel!5e0!3m2!1sen!2sin!4v1632476420684!5m2!1sen!2sin&rel=0')),
                ('Agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Flatmates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.flatmatechoice')),
            ],
            options={
                'permissions': (('can_publish_flatmateprojectdetail', 'Can publish flatmate project detail'),),
            },
        ),
        migrations.CreateModel(
            name='FlatmateHouseRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('flatmate_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.flatmateprojectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='FlatmateGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery_images')),
                ('flatmate_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.flatmateprojectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='FlatmateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('flatmate_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.flatmateprojectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='FlatmateCommonRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('flatmate_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.flatmateprojectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='FlatmateAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Amenities_images')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('flatmate_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.flatmateprojectdetail')),
            ],
        ),
    ]
