# Generated by Django 4.1 on 2023-10-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0002_flatmatechoice_alter_commercialprojectdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Private Room', 'Private Room'), ('Food Available', 'Food Available')], default='Boys', max_length=20),
        ),
    ]
