# Generated by Django 4.1 on 2023-10-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0004_rename_flatmateamenities_flatmateservices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialprojectdetail',
            name='commercial_type',
            field=models.CharField(choices=[('Recently Added properties for Rent', 'Recently Added properties for Rent'), ('Recently Added properties for sale', 'Recently Added properties for sale')], default='Recently Added properties for sale', max_length=40),
        ),
        migrations.AlterField(
            model_name='developerdetails',
            name='developer_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Buy', 'Buy')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Buy', 'Buy'), ('Commercial', 'Commercial'), ('Flatmate', 'Flatmate'), ('Rent', 'Rent')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Private Room', 'Private Room'), ('Girls', 'Girls'), ('Boys', 'Boys'), ('Food Available', 'Food Available')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmateprojectdetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flat_images'),
        ),
        migrations.AlterField(
            model_name='flatmateprojectdetail',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='flat'),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Buy', 'Buy'), ('Commercial', 'Commercial'), ('Flatmate', 'Flatmate'), ('Rent', 'Rent')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsdetails',
            name='news_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Buy', 'Buy'), ('Commercial', 'Commercial'), ('Flatmate', 'Flatmate'), ('Rent', 'Rent')], default='Buy', max_length=20),
        ),
    ]
