# Generated by Django 4.1 on 2023-10-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0005_alter_commercialprojectdetail_commercial_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialprojectdetail',
            name='commercial_type',
            field=models.CharField(choices=[('Recently Added properties for sale', 'Recently Added properties for sale'), ('Recently Added properties for Rent', 'Recently Added properties for Rent')], default='Recently Added properties for sale', max_length=40),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Buy', 'Buy'), ('Rent', 'Rent'), ('Plots', 'Plots'), ('Flatmate', 'Flatmate')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Private Room', 'Private Room'), ('Boys', 'Boys'), ('Food Available', 'Food Available'), ('Girls', 'Girls')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmateservices',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Services_images'),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Buy', 'Buy'), ('Rent', 'Rent'), ('Plots', 'Plots'), ('Flatmate', 'Flatmate')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsdetails',
            name='news_type',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Buy', 'Buy'), ('Rent', 'Rent'), ('Plots', 'Plots'), ('Flatmate', 'Flatmate')], default='Buy', max_length=20),
        ),
    ]
