# Generated by Django 4.1 on 2023-10-27 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0007_alter_commercialprojectdetail_commercial_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerdetails',
            name='developer_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Commercial', 'Commercial'), ('Rent', 'Rent'), ('Flatmate', 'Flatmate'), ('Buy', 'Buy')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Food Available', 'Food Available'), ('Girls', 'Girls'), ('Private Room', 'Private Room')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Commercial', 'Commercial'), ('Rent', 'Rent'), ('Flatmate', 'Flatmate'), ('Buy', 'Buy')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsdetails',
            name='news_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Commercial', 'Commercial'), ('Rent', 'Rent'), ('Flatmate', 'Flatmate'), ('Buy', 'Buy')], default='Buy', max_length=20),
        ),
        migrations.CreateModel(
            name='FlatmateServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Services_images')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('flatmate_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.flatmateprojectdetail')),
            ],
        ),
    ]
