# Generated by Django 4.1 on 2023-10-27 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0008_alter_developerdetails_developer_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatmateAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Amenities_images')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('flatmate_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.flatmateprojectdetail')),
            ],
        ),
        migrations.AlterField(
            model_name='commercialprojectdetail',
            name='commercial_type',
            field=models.CharField(choices=[('Recently Added properties for sale', 'Recently Added properties for sale'), ('Recently Added properties for Rent', 'Recently Added properties for Rent')], default='Recently Added properties for sale', max_length=40),
        ),
        migrations.AlterField(
            model_name='developerdetails',
            name='developer_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Buy', 'Buy')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Rent', 'Rent'), ('Commercial', 'Commercial'), ('Buy', 'Buy'), ('Flatmate', 'Flatmate')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Private Room', 'Private Room'), ('Food Available', 'Food Available'), ('Boys', 'Boys'), ('Girls', 'Girls')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Rent', 'Rent'), ('Commercial', 'Commercial'), ('Buy', 'Buy'), ('Flatmate', 'Flatmate')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsdetails',
            name='news_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Rent', 'Rent'), ('Commercial', 'Commercial'), ('Buy', 'Buy'), ('Flatmate', 'Flatmate')], default='Buy', max_length=20),
        ),
        migrations.DeleteModel(
            name='FlatmateServices',
        ),
    ]
