# Generated by Django 4.1 on 2023-10-28 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0011_flatmateamenities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoysFlatmate',
            fields=[
                ('flatmatechoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='housingapp.flatmatechoice')),
            ],
            bases=('housingapp.flatmatechoice',),
        ),
        migrations.CreateModel(
            name='FoodAvailableFlatmate',
            fields=[
                ('flatmatechoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='housingapp.flatmatechoice')),
            ],
            bases=('housingapp.flatmatechoice',),
        ),
        migrations.CreateModel(
            name='GirlsFlatmate',
            fields=[
                ('flatmatechoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='housingapp.flatmatechoice')),
            ],
            bases=('housingapp.flatmatechoice',),
        ),
        migrations.CreateModel(
            name='PrivateRoomFlatmate',
            fields=[
                ('flatmatechoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='housingapp.flatmatechoice')),
            ],
            bases=('housingapp.flatmatechoice',),
        ),
        migrations.RemoveField(
            model_name='flatmatechoice',
            name='flatmate_choices',
        ),
        migrations.AlterField(
            model_name='commercialprojectdetail',
            name='commercial_type',
            field=models.CharField(choices=[('Recently Added properties for sale', 'Recently Added properties for sale'), ('Recently Added properties for Rent', 'Recently Added properties for Rent')], default='Recently Added properties for sale', max_length=40),
        ),
        migrations.AlterField(
            model_name='developerdetails',
            name='developer_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Plots', 'Plots'), ('Flatmate', 'Flatmate'), ('Commercial', 'Commercial'), ('Rent', 'Rent')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Plots', 'Plots'), ('Flatmate', 'Flatmate'), ('Commercial', 'Commercial'), ('Rent', 'Rent')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsdetails',
            name='news_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Plots', 'Plots'), ('Flatmate', 'Flatmate'), ('Commercial', 'Commercial'), ('Rent', 'Rent')], default='Buy', max_length=20),
        ),
    ]
