# Generated by Django 4.2.6 on 2023-10-30 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0017_alter_commercialprojectdetail_commercial_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialprojectdetail',
            name='commercial_type',
            field=models.CharField(choices=[('Recently Added properties for Rent', 'Recently Added properties for Rent'), ('Recently Added properties for sale', 'Recently Added properties for sale')], default='Recently Added properties for sale', max_length=40),
        ),
        migrations.AlterField(
            model_name='developerdetails',
            name='developer_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Buy', 'Buy'), ('Commercial', 'Commercial'), ('Flatmate', 'Flatmate'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Private Room', 'Private Room'), ('Boys', 'Boys'), ('Girls', 'Girls'), ('Food Available', 'Food Available')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Buy', 'Buy'), ('Commercial', 'Commercial'), ('Flatmate', 'Flatmate'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='likedproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.plotsprojectdetail'),
        ),
        migrations.AlterField(
            model_name='newsdetails',
            name='news_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Buy', 'Buy'), ('Commercial', 'Commercial'), ('Flatmate', 'Flatmate'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
    ]
