# Generated by Django 4.2.7 on 2023-11-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0020_alter_commercialprojectdetail_commercial_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plotlikedproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='plotlikedproject',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rentlikedproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='rentlikedproject',
            name='user',
        ),
        migrations.AlterField(
            model_name='commercialprojectdetail',
            name='commercial_type',
            field=models.CharField(choices=[('Recently Added properties for sale', 'Recently Added properties for sale'), ('Recently Added properties for Rent', 'Recently Added properties for Rent')], default='Recently Added properties for sale', max_length=40),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Flatmate', 'Flatmate'), ('Buy', 'Buy'), ('Commercial', 'Commercial'), ('Rent', 'Rent')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Private Room', 'Private Room'), ('Boys', 'Boys'), ('Girls', 'Girls'), ('Food Available', 'Food Available')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Flatmate', 'Flatmate'), ('Buy', 'Buy'), ('Commercial', 'Commercial'), ('Rent', 'Rent')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsdetails',
            name='news_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Flatmate', 'Flatmate'), ('Buy', 'Buy'), ('Commercial', 'Commercial'), ('Rent', 'Rent')], default='Buy', max_length=20),
        ),
        migrations.DeleteModel(
            name='CommercialLikedProject',
        ),
        migrations.DeleteModel(
            name='PlotLikedProject',
        ),
        migrations.DeleteModel(
            name='RentLikedProject',
        ),
    ]
