# Generated by Django 4.2.7 on 2023-11-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0022_banner_alter_commercialprojectdetail_commercial_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='Banner_image',
            field=models.ImageField(upload_to='Banner_images'),
        ),
        migrations.AlterField(
            model_name='commercialprojectdetail',
            name='commercial_type',
            field=models.CharField(choices=[('Recently Added properties for sale', 'Recently Added properties for sale'), ('Recently Added properties for Rent', 'Recently Added properties for Rent')], default='Recently Added properties for sale', max_length=40),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Flatmate', 'Flatmate'), ('Plots', 'Plots'), ('Buy', 'Buy'), ('Commercial', 'Commercial')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Girls', 'Girls'), ('Food Available', 'Food Available'), ('Private Room', 'Private Room'), ('Boys', 'Boys')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Flatmate', 'Flatmate'), ('Plots', 'Plots'), ('Buy', 'Buy'), ('Commercial', 'Commercial')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsdetails',
            name='news_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Flatmate', 'Flatmate'), ('Plots', 'Plots'), ('Buy', 'Buy'), ('Commercial', 'Commercial')], default='Buy', max_length=20),
        ),
    ]
