# Generated by Django 4.2.7 on 2023-11-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0029_alter_faq_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='locality_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='locality_video',
            field=models.TextField(default='https://www.youtube.com/embed/tgbNymZ7vqY'),
        ),
        migrations.AlterField(
            model_name='developerdetails',
            name='developer_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Buy', 'Buy')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Buy', 'Buy'), ('Flatmate', 'Flatmate'), ('Rent', 'Rent'), ('Commercial', 'Commercial')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Food Available', 'Food Available'), ('Private Room', 'Private Room'), ('Boys', 'Boys'), ('Girls', 'Girls')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Buy', 'Buy'), ('Flatmate', 'Flatmate'), ('Rent', 'Rent'), ('Commercial', 'Commercial')], default='Buy', max_length=20),
        ),
    ]
