# Generated by Django 4.2.7 on 2023-11-14 11:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0030_projectdetail_locality_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Commercial', 'Commercial'), ('Rent', 'Rent'), ('Plots', 'Plots'), ('Flatmate', 'Flatmate')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Food Available', 'Food Available'), ('Girls', 'Girls'), ('Boys', 'Boys'), ('Private Room', 'Private Room')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Commercial', 'Commercial'), ('Rent', 'Rent'), ('Plots', 'Plots'), ('Flatmate', 'Flatmate')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
