# Generated by Django 4.2.7 on 2023-11-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0031_alter_featuredcollections_feature_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='masterplan',
            field=models.ImageField(blank=True, null=True, upload_to='masterplan_images'),
        ),
        migrations.AlterField(
            model_name='commercialprojectdetail',
            name='commercial_type',
            field=models.CharField(choices=[('Recently Added properties for Rent', 'Recently Added properties for Rent'), ('Recently Added properties for sale', 'Recently Added properties for sale')], default='Recently Added properties for sale', max_length=40),
        ),
        migrations.AlterField(
            model_name='developerdetails',
            name='developer_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent'), ('Plots', 'Plots'), ('Commercial', 'Commercial'), ('Flatmate', 'Flatmate')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Food Available', 'Food Available'), ('Girls', 'Girls'), ('Private Room', 'Private Room')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent'), ('Plots', 'Plots'), ('Commercial', 'Commercial'), ('Flatmate', 'Flatmate')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='possession_status',
            field=models.CharField(choices=[('Ready to move', 'Ready to move'), ('Beyond 3 years', 'Beyond 3 years'), ('In 3 years', 'In 3 years')], default='Ready to move', max_length=20),
        ),
    ]
