# Generated by Django 4.2.7 on 2023-11-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0032_projectdetail_masterplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='configuration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commercialprojectdetail',
            name='commercial_type',
            field=models.CharField(choices=[('Recently Added properties for sale', 'Recently Added properties for sale'), ('Recently Added properties for Rent', 'Recently Added properties for Rent')], default='Recently Added properties for sale', max_length=40),
        ),
        migrations.AlterField(
            model_name='developerdetails',
            name='developer_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Buy', 'Buy')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Flatmate', 'Flatmate'), ('Rent', 'Rent'), ('Buy', 'Buy'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Private Room', 'Private Room'), ('Food Available', 'Food Available'), ('Girls', 'Girls')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Flatmate', 'Flatmate'), ('Rent', 'Rent'), ('Buy', 'Buy'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
    ]
