# Generated by Django 4.2.7 on 2023-11-14 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0033_floorplan_configuration_floorplan_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorplan',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='image',
        ),
        migrations.AlterField(
            model_name='developerdetails',
            name='developer_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Commercial', 'Commercial'), ('Plots', 'Plots'), ('Flatmate', 'Flatmate'), ('Rent', 'Rent')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Food Available', 'Food Available'), ('Girls', 'Girls'), ('Boys', 'Boys'), ('Private Room', 'Private Room')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Commercial', 'Commercial'), ('Plots', 'Plots'), ('Flatmate', 'Flatmate'), ('Rent', 'Rent')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='possession_status',
            field=models.CharField(choices=[('In 3 years', 'In 3 years'), ('Beyond 3 years', 'Beyond 3 years'), ('Ready to move', 'Ready to move')], default='Ready to move', max_length=20),
        ),
        migrations.CreateModel(
            name='Floorplan_configurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='floorplan_images')),
                ('configurations', models.CharField(blank=True, max_length=100, null=True)),
                ('floorplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.floorplan')),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.projectdetail')),
            ],
        ),
    ]
