# Generated by Django 4.2.7 on 2023-11-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0034_remove_floorplan_configuration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorplan_configurations',
            name='project_details',
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Flatmate', 'Flatmate'), ('Commercial', 'Commercial'), ('Rent', 'Rent'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Food Available', 'Food Available'), ('Private Room', 'Private Room'), ('Girls', 'Girls')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Flatmate', 'Flatmate'), ('Commercial', 'Commercial'), ('Rent', 'Rent'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='possession_status',
            field=models.CharField(choices=[('Ready to move', 'Ready to move'), ('Beyond 3 years', 'Beyond 3 years'), ('In 3 years', 'In 3 years')], default='Ready to move', max_length=20),
        ),
    ]
