# Generated by Django 4.2.7 on 2023-11-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0036_floorplan_configurations_project_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorplan',
            name='name',
        ),
        migrations.AddField(
            model_name='floorplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='floorplan_images'),
        ),
        migrations.AlterField(
            model_name='commercialprojectdetail',
            name='commercial_type',
            field=models.CharField(choices=[('Recently Added properties for Rent', 'Recently Added properties for Rent'), ('Recently Added properties for sale', 'Recently Added properties for sale')], default='Recently Added properties for sale', max_length=40),
        ),
        migrations.AlterField(
            model_name='developerdetails',
            name='developer_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Buy', 'Buy')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent'), ('Flatmate', 'Flatmate'), ('Commercial', 'Commercial'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Food Available', 'Food Available'), ('Private Room', 'Private Room'), ('Girls', 'Girls'), ('Boys', 'Boys')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent'), ('Flatmate', 'Flatmate'), ('Commercial', 'Commercial'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.DeleteModel(
            name='Floorplan_configurations',
        ),
    ]
