# Generated by Django 4.2.7 on 2023-11-14 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0037_remove_floorplan_name_floorplan_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorplan',
            name='image',
        ),
        migrations.AddField(
            model_name='floorplan',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='developerdetails',
            name='developer_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Buy', 'Buy'), ('Plots', 'Plots'), ('Flatmate', 'Flatmate'), ('Rent', 'Rent')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Food Available', 'Food Available'), ('Private Room', 'Private Room')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Buy', 'Buy'), ('Plots', 'Plots'), ('Flatmate', 'Flatmate'), ('Rent', 'Rent')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='possession_status',
            field=models.CharField(choices=[('Beyond 3 years', 'Beyond 3 years'), ('In 3 years', 'In 3 years'), ('Ready to move', 'Ready to move')], default='Ready to move', max_length=20),
        ),
        migrations.CreateModel(
            name='Floorplan_configurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='floorplan_images')),
                ('configurations', models.CharField(blank=True, max_length=100, null=True)),
                ('floorplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.floorplan')),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.projectdetail')),
            ],
        ),
    ]
