# Generated by Django 4.2.7 on 2023-11-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0039_alter_featuredcollections_feature_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotsprojectdetail',
            name='masterplan',
            field=models.ImageField(blank=True, null=True, upload_to='masterplan_images'),
        ),
        migrations.AlterField(
            model_name='developerdetails',
            name='developer_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Buy', 'Buy')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Flatmate', 'Flatmate'), ('Buy', 'Buy'), ('Commercial', 'Commercial'), ('Rent', 'Rent')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Private Room', 'Private Room'), ('Girls', 'Girls'), ('Food Available', 'Food Available')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Flatmate', 'Flatmate'), ('Buy', 'Buy'), ('Commercial', 'Commercial'), ('Rent', 'Rent')], default='Buy', max_length=20),
        ),
    ]
