# Generated by Django 4.2.7 on 2023-11-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0040_plotsprojectdetail_masterplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotsprojectdetail',
            name='locality_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plotsprojectdetail',
            name='locality_video',
            field=models.TextField(default='https://www.youtube.com/embed/tgbNymZ7vqY'),
        ),
        migrations.AddField(
            model_name='plotsprojectdetail',
            name='possession_status',
            field=models.CharField(choices=[('Ready to move', 'Ready to move'), ('In 3 years', 'In 3 years'), ('Beyond 3 years', 'Beyond 3 years')], default='Ready to move', max_length=20),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Commercial', 'Commercial'), ('Flatmate', 'Flatmate'), ('Rent', 'Rent'), ('Buy', 'Buy')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Food Available', 'Food Available'), ('Private Room', 'Private Room')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Commercial', 'Commercial'), ('Flatmate', 'Flatmate'), ('Rent', 'Rent'), ('Buy', 'Buy')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='possession_status',
            field=models.CharField(choices=[('Ready to move', 'Ready to move'), ('In 3 years', 'In 3 years'), ('Beyond 3 years', 'Beyond 3 years')], default='Ready to move', max_length=20),
        ),
    ]
