# Generated by Django 4.2.7 on 2023-11-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0045_rentprojectdetail_locality_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercialprojectdetail',
            old_name='project_by',
            new_name='developer_name',
        ),
        migrations.RenameField(
            model_name='plotsprojectdetail',
            old_name='configuration',
            new_name='Configuration',
        ),
        migrations.RenameField(
            model_name='plotsprojectdetail',
            old_name='project_by',
            new_name='developer_name',
        ),
        migrations.RenameField(
            model_name='rentprojectdetail',
            old_name='configuration',
            new_name='Configuration',
        ),
        migrations.AlterField(
            model_name='commercialprojectdetail',
            name='commercial_type',
            field=models.CharField(choices=[('Recently Added properties for sale', 'Recently Added properties for sale'), ('Recently Added properties for Rent', 'Recently Added properties for Rent')], default='Recently Added properties for sale', max_length=40),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent'), ('Commercial', 'Commercial'), ('Flatmate', 'Flatmate'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Private Room', 'Private Room'), ('Food Available', 'Food Available'), ('Boys', 'Boys'), ('Girls', 'Girls')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent'), ('Commercial', 'Commercial'), ('Flatmate', 'Flatmate'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
    ]
