# Generated by Django 4.2.7 on 2023-11-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0046_rename_project_by_commercialprojectdetail_developer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floorplan',
            old_name='name',
            new_name='sq_ft',
        ),
        migrations.AddField(
            model_name='floorplan',
            name='Configuration',
            field=models.CharField(choices=[('2BHK', '2BHK'), ('4BHK', '4BHK'), ('3BHK', '3BHK'), ('1BHK', '1BHK')], default='1BHK', max_length=20),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='floorplan_images'),
        ),
        migrations.AlterField(
            model_name='commercialprojectdetail',
            name='commercial_type',
            field=models.CharField(choices=[('Recently Added properties for Rent', 'Recently Added properties for Rent'), ('Recently Added properties for sale', 'Recently Added properties for sale')], default='Recently Added properties for sale', max_length=40),
        ),
        migrations.AlterField(
            model_name='developerdetails',
            name='developer_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Buy', 'Buy')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Rent', 'Rent'), ('Plots', 'Plots'), ('Buy', 'Buy'), ('Flatmate', 'Flatmate')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Girls', 'Girls'), ('Private Room', 'Private Room'), ('Food Available', 'Food Available'), ('Boys', 'Boys')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Rent', 'Rent'), ('Plots', 'Plots'), ('Buy', 'Buy'), ('Flatmate', 'Flatmate')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='plotsprojectdetail',
            name='possession_status',
            field=models.CharField(choices=[('In 3 years', 'In 3 years'), ('Beyond 3 years', 'Beyond 3 years'), ('Ready to move', 'Ready to move')], default='Ready to move', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='possession_status',
            field=models.CharField(choices=[('In 3 years', 'In 3 years'), ('Beyond 3 years', 'Beyond 3 years'), ('Ready to move', 'Ready to move')], default='Ready to move', max_length=20),
        ),
        migrations.DeleteModel(
            name='Floorplan_configurations',
        ),
    ]
