# Generated by Django 4.2.7 on 2023-12-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0049_alter_commercialprojectdetail_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerdetails',
            name='developer_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Plots', 'Plots'), ('Flatmate', 'Flatmate'), ('Buy', 'Buy'), ('Commercial', 'Commercial')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Food Available', 'Food Available'), ('Private Room', 'Private Room'), ('Boys', 'Boys'), ('Girls', 'Girls')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='Configuration',
            field=models.CharField(choices=[('3BHK', '3BHK'), ('4BHK', '4BHK'), ('1BHK', '1BHK'), ('2BHK', '2BHK')], default='1BHK', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Plots', 'Plots'), ('Flatmate', 'Flatmate'), ('Buy', 'Buy'), ('Commercial', 'Commercial')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsdetails',
            name='main_title',
            field=models.CharField(max_length=500),
        ),
    ]
