# Generated by Django 4.2.7 on 2023-12-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0051_contact_agent_contact_project_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Agent',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent'), ('Flatmate', 'Flatmate'), ('Commercial', 'Commercial'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Private Room', 'Private Room'), ('Food Available', 'Food Available'), ('Girls', 'Girls')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='Configuration',
            field=models.CharField(choices=[('4BHK', '4BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('1BHK', '1BHK')], default='1BHK', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent'), ('Flatmate', 'Flatmate'), ('Commercial', 'Commercial'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='plotsprojectdetail',
            name='possession_status',
            field=models.CharField(choices=[('In 3 years', 'In 3 years'), ('Ready to move', 'Ready to move'), ('Beyond 3 years', 'Beyond 3 years')], default='Ready to move', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='possession_status',
            field=models.CharField(choices=[('In 3 years', 'In 3 years'), ('Ready to move', 'Ready to move'), ('Beyond 3 years', 'Beyond 3 years')], default='Ready to move', max_length=20),
        ),
    ]
