# Generated by Django 4.2.7 on 2023-12-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0054_contact_project_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='project_details',
        ),
        migrations.AlterField(
            model_name='commercialprojectdetail',
            name='commercial_type',
            field=models.CharField(choices=[('Recently Added properties for Rent', 'Recently Added properties for Rent'), ('Recently Added properties for sale', 'Recently Added properties for sale')], default='Recently Added properties for sale', max_length=40),
        ),
        migrations.AlterField(
            model_name='developerdetails',
            name='developer_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Buy', 'Buy')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Buy', 'Buy'), ('Commercial', 'Commercial'), ('Plots', 'Plots'), ('Flatmate', 'Flatmate')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Food Available', 'Food Available'), ('Girls', 'Girls'), ('Boys', 'Boys'), ('Private Room', 'Private Room')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='Configuration',
            field=models.CharField(choices=[('3BHK', '3BHK'), ('1BHK', '1BHK'), ('2BHK', '2BHK'), ('4BHK', '4BHK')], default='1BHK', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Buy', 'Buy'), ('Commercial', 'Commercial'), ('Plots', 'Plots'), ('Flatmate', 'Flatmate')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='plotsprojectdetail',
            name='possession_status',
            field=models.CharField(choices=[('Ready to move', 'Ready to move'), ('Beyond 3 years', 'Beyond 3 years'), ('In 3 years', 'In 3 years')], default='Ready to move', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='possession_status',
            field=models.CharField(choices=[('Ready to move', 'Ready to move'), ('Beyond 3 years', 'Beyond 3 years'), ('In 3 years', 'In 3 years')], default='Ready to move', max_length=20),
        ),
    ]
