# Generated by Django 4.2.7 on 2023-12-13 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0057_alter_developerdetails_developer_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedproject',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='savedproject',
            name='object_id',
        ),
        migrations.AddField(
            model_name='savedproject',
            name='commercialproject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='housingapp.commercialprojectdetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedproject',
            name='plotsproject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='housingapp.plotsprojectdetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedproject',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='housingapp.projectdetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedproject',
            name='rentproject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='housingapp.rentprojectdetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commercialprojectdetail',
            name='commercial_type',
            field=models.CharField(choices=[('Recently Added properties for sale', 'Recently Added properties for sale'), ('Recently Added properties for Rent', 'Recently Added properties for Rent')], default='Recently Added properties for sale', max_length=40),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Flatmate', 'Flatmate'), ('Buy', 'Buy'), ('Plots', 'Plots'), ('Commercial', 'Commercial'), ('Rent', 'Rent')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Private Room', 'Private Room'), ('Food Available', 'Food Available'), ('Girls', 'Girls')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='Configuration',
            field=models.CharField(choices=[('1BHK', '1BHK'), ('2BHK', '2BHK'), ('4BHK', '4BHK'), ('3BHK', '3BHK')], default='1BHK', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Flatmate', 'Flatmate'), ('Buy', 'Buy'), ('Plots', 'Plots'), ('Commercial', 'Commercial'), ('Rent', 'Rent')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='plotsprojectdetail',
            name='possession_status',
            field=models.CharField(choices=[('In 3 years', 'In 3 years'), ('Beyond 3 years', 'Beyond 3 years'), ('Ready to move', 'Ready to move')], default='Ready to move', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='possession_status',
            field=models.CharField(choices=[('In 3 years', 'In 3 years'), ('Beyond 3 years', 'Beyond 3 years'), ('Ready to move', 'Ready to move')], default='Ready to move', max_length=20),
        ),
    ]
