# Generated by Django 4.2.7 on 2023-12-13 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0058_remove_savedproject_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='commercialproject_details',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='housingapp.commercialprojectdetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='plotsproject_details',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='housingapp.plotsprojectdetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='rentproject_details',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='housingapp.rentprojectdetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Plots', 'Plots'), ('Flatmate', 'Flatmate'), ('Commercial', 'Commercial'), ('Buy', 'Buy')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Girls', 'Girls'), ('Boys', 'Boys'), ('Private Room', 'Private Room'), ('Food Available', 'Food Available')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='Configuration',
            field=models.CharField(choices=[('4BHK', '4BHK'), ('3BHK', '3BHK'), ('2BHK', '2BHK'), ('1BHK', '1BHK')], default='1BHK', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Plots', 'Plots'), ('Flatmate', 'Flatmate'), ('Commercial', 'Commercial'), ('Buy', 'Buy')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='plotsprojectdetail',
            name='possession_status',
            field=models.CharField(choices=[('Beyond 3 years', 'Beyond 3 years'), ('In 3 years', 'In 3 years'), ('Ready to move', 'Ready to move')], default='Ready to move', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='possession_status',
            field=models.CharField(choices=[('Beyond 3 years', 'Beyond 3 years'), ('In 3 years', 'In 3 years'), ('Ready to move', 'Ready to move')], default='Ready to move', max_length=20),
        ),
    ]
