# Generated by Django 4.2.7 on 2023-12-13 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0060_alter_featuredcollections_feature_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='commercialproject_details',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='plotsproject_details',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='rentproject_details',
        ),
        migrations.AlterField(
            model_name='developerdetails',
            name='developer_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent'), ('Commercial', 'Commercial'), ('Flatmate', 'Flatmate'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Private Room', 'Private Room'), ('Food Available', 'Food Available'), ('Boys', 'Boys'), ('Girls', 'Girls')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='Configuration',
            field=models.CharField(choices=[('2BHK', '2BHK'), ('1BHK', '1BHK'), ('3BHK', '3BHK'), ('4BHK', '4BHK')], default='1BHK', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent'), ('Commercial', 'Commercial'), ('Flatmate', 'Flatmate'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.CreateModel(
            name='HousingContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(default='', max_length=40)),
                ('plotsproject_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.plotsprojectdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
