# Generated by Django 4.2.7 on 2023-12-13 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0061_remove_contact_commercialproject_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingcontact',
            name='plotsproject_details',
        ),
        migrations.AddField(
            model_name='housingcontact',
            name='housing_experts',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='housingapp.housingexperts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='developerdetails',
            name='developer_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Buy', 'Buy')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Flatmate', 'Flatmate'), ('Plots', 'Plots'), ('Commercial', 'Commercial'), ('Rent', 'Rent'), ('Buy', 'Buy')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Private Room', 'Private Room'), ('Food Available', 'Food Available'), ('Girls', 'Girls'), ('Boys', 'Boys')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='Configuration',
            field=models.CharField(choices=[('1BHK', '1BHK'), ('3BHK', '3BHK'), ('2BHK', '2BHK'), ('4BHK', '4BHK')], default='1BHK', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Flatmate', 'Flatmate'), ('Plots', 'Plots'), ('Commercial', 'Commercial'), ('Rent', 'Rent'), ('Buy', 'Buy')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='plotsprojectdetail',
            name='possession_status',
            field=models.CharField(choices=[('Beyond 3 years', 'Beyond 3 years'), ('Ready to move', 'Ready to move'), ('In 3 years', 'In 3 years')], default='Ready to move', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='possession_status',
            field=models.CharField(choices=[('Beyond 3 years', 'Beyond 3 years'), ('Ready to move', 'Ready to move'), ('In 3 years', 'In 3 years')], default='Ready to move', max_length=20),
        ),
    ]
