# Generated by Django 4.2.7 on 2023-12-13 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0062_remove_housingcontact_plotsproject_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerdetails',
            name='developer_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Commercial', 'Commercial'), ('Rent', 'Rent'), ('Flatmate', 'Flatmate'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Private Room', 'Private Room'), ('Food Available', 'Food Available'), ('Girls', 'Girls')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='Configuration',
            field=models.CharField(choices=[('3BHK', '3BHK'), ('4BHK', '4BHK'), ('1BHK', '1BHK'), ('2BHK', '2BHK')], default='1BHK', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Commercial', 'Commercial'), ('Rent', 'Rent'), ('Flatmate', 'Flatmate'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='plotsprojectdetail',
            name='possession_status',
            field=models.CharField(choices=[('Ready to move', 'Ready to move'), ('Beyond 3 years', 'Beyond 3 years'), ('In 3 years', 'In 3 years')], default='Ready to move', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='possession_status',
            field=models.CharField(choices=[('Ready to move', 'Ready to move'), ('Beyond 3 years', 'Beyond 3 years'), ('In 3 years', 'In 3 years')], default='Ready to move', max_length=20),
        ),
        migrations.CreateModel(
            name='RentLikedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('rent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.rentprojectdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlotLikedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('plot_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.projectdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommercialLikedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('commercial_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.projectdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
