# Generated by Django 4.2.7 on 2023-12-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0063_alter_developerdetails_developer_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commerciallikedproject',
            old_name='commercial_project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='plotlikedproject',
            old_name='plot_project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='rentlikedproject',
            old_name='rent_project',
            new_name='project',
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Flatmate', 'Flatmate'), ('Commercial', 'Commercial'), ('Buy', 'Buy'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Private Room', 'Private Room'), ('Food Available', 'Food Available')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='Configuration',
            field=models.CharField(choices=[('3BHK', '3BHK'), ('1BHK', '1BHK'), ('2BHK', '2BHK'), ('4BHK', '4BHK')], default='1BHK', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Flatmate', 'Flatmate'), ('Commercial', 'Commercial'), ('Buy', 'Buy'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='plotsprojectdetail',
            name='possession_status',
            field=models.CharField(choices=[('Beyond 3 years', 'Beyond 3 years'), ('In 3 years', 'In 3 years'), ('Ready to move', 'Ready to move')], default='Ready to move', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='possession_status',
            field=models.CharField(choices=[('Beyond 3 years', 'Beyond 3 years'), ('In 3 years', 'In 3 years'), ('Ready to move', 'Ready to move')], default='Ready to move', max_length=20),
        ),
    ]
