# Generated by Django 4.2.7 on 2023-12-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0071_remove_housingexperts_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Rent', 'Rent'), ('Commercial', 'Commercial'), ('Buy', 'Buy')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Private Room', 'Private Room'), ('Boys', 'Boys'), ('Girls', 'Girls'), ('Food Available', 'Food Available')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='Configuration',
            field=models.CharField(choices=[('4BHK', '4BHK'), ('2BHK', '2BHK'), ('1BHK', '1BHK'), ('3BHK', '3BHK')], default='1BHK', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Rent', 'Rent'), ('Commercial', 'Commercial'), ('Buy', 'Buy')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='plotsprojectdetail',
            name='possession_status',
            field=models.CharField(choices=[('Ready to move', 'Ready to move'), ('Beyond 3 years', 'Beyond 3 years'), ('In 3 years', 'In 3 years')], default='Ready to move', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='possession_status',
            field=models.CharField(choices=[('Ready to move', 'Ready to move'), ('Beyond 3 years', 'Beyond 3 years'), ('In 3 years', 'In 3 years')], default='Ready to move', max_length=20),
        ),
    ]
