# Generated by Django 4.2.7 on 2023-12-14 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0073_alter_commercialprojectdetail_commercial_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='Experts',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='housingapp.housingexperts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commercialprojectdetail',
            name='commercial_type',
            field=models.CharField(choices=[('Recently Added properties for Rent', 'Recently Added properties for Rent'), ('Recently Added properties for sale', 'Recently Added properties for sale')], default='Recently Added properties for sale', max_length=40),
        ),
        migrations.AlterField(
            model_name='developerdetails',
            name='developer_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Buy', 'Buy')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Buy', 'Buy'), ('Rent', 'Rent'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Food Available', 'Food Available'), ('Girls', 'Girls'), ('Private Room', 'Private Room'), ('Boys', 'Boys')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='Configuration',
            field=models.CharField(choices=[('4BHK', '4BHK'), ('2BHK', '2BHK'), ('1BHK', '1BHK'), ('3BHK', '3BHK')], default='1BHK', max_length=20),
        ),
    ]
