# Generated by Django 4.2.7 on 2023-12-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0077_alter_commercialprojectdetail_commercial_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerdetails',
            name='developer_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Plots', 'Plots')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Buy', 'Buy'), ('Plots', 'Plots'), ('Commercial', 'Commercial')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Private Room', 'Private Room'), ('Food Available', 'Food Available')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='Configuration',
            field=models.CharField(choices=[('2BHK', '2BHK'), ('1BHK', '1BHK'), ('3BHK', '3BHK'), ('4BHK', '4BHK')], default='1BHK', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=models.CharField(blank=True, choices=[('Buy', 'Buy'), ('Rent', 'Rent'), ('Commercial', 'Commercial'), ('Plots', 'Plots')], max_length=255),
        ),
        migrations.AlterField(
            model_name='plotsprojectdetail',
            name='possession_status',
            field=models.CharField(choices=[('Beyond 3 years', 'Beyond 3 years'), ('Ready to move', 'Ready to move'), ('In 3 years', 'In 3 years')], default='Ready to move', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='possession_status',
            field=models.CharField(choices=[('Beyond 3 years', 'Beyond 3 years'), ('Ready to move', 'Ready to move'), ('In 3 years', 'In 3 years')], default='Ready to move', max_length=20),
        ),
    ]
