# Generated by Django 5.0 on 2023-12-14 08:33

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0080_alter_commercialprojectdetail_commercial_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Plots', 'Plots'), ('Commercial', 'Commercial'), ('Buy', 'Buy'), ('Rent', 'Rent')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Food Available', 'Food Available'), ('Private Room', 'Private Room')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='Configuration',
            field=models.CharField(choices=[('1BHK', '1BHK'), ('4BHK', '4BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK')], default='1BHK', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingexperts',
            name='expert_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Plots', 'Plots'), ('Commercial', 'Commercial'), ('Buy', 'Buy'), ('Rent', 'Rent')], default=[], max_length=2048),
        ),
    ]
