# Generated by Django 5.0 on 2023-12-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingapp', '0083_remove_housingexperts_expert_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialprojectdetail',
            name='commercial_type',
            field=models.CharField(choices=[('Recently Added properties for Rent', 'Recently Added properties for Rent'), ('Recently Added properties for sale', 'Recently Added properties for sale')], default='Recently Added properties for sale', max_length=40),
        ),
        migrations.AlterField(
            model_name='featuredcollections',
            name='feature_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Buy', 'Buy'), ('Plots', 'Plots'), ('Commercial', 'Commercial')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='flatmatechoice',
            name='flatmate_choices',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Private Room', 'Private Room'), ('Food Available', 'Food Available')], default='Boys', max_length=20),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='Configuration',
            field=models.CharField(choices=[('2BHK', '2BHK'), ('4BHK', '4BHK'), ('3BHK', '3BHK'), ('1BHK', '1BHK')], default='1BHK', max_length=20),
        ),
        migrations.AlterField(
            model_name='plotsprojectdetail',
            name='possession_status',
            field=models.CharField(choices=[('In 3 years', 'In 3 years'), ('Beyond 3 years', 'Beyond 3 years'), ('Ready to move', 'Ready to move')], default='Ready to move', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='possession_status',
            field=models.CharField(choices=[('In 3 years', 'In 3 years'), ('Beyond 3 years', 'Beyond 3 years'), ('Ready to move', 'Ready to move')], default='Ready to move', max_length=20),
        ),
    ]
